### PR TITLE
Fixed vertical alignment

### PR DESCRIPTION
**Pull request by Ian-Stewart-Binks**
This pull request fixes the vertical alignment in the weefig project.

### CODE REVIEW

**Comment by emmettu** [comment]
Hi Ian,

Are you the new fig intern?
Confused as to why you've included your name in the author header.
This project is not adding authors to the header at the moment.

Additionally, I haven't granted anyone code review privileges, so if you could please include a descriptive commit message instead that would be great.

Thank you,

Emmett Underhill

**Comment by Ian-Stewart-Binks** [comment]
Hi @emmettu,

I've removed my name from the header.

Sincerely,
Ian

**Comment by emmettu** [comment]
Ian you seem to have set the **author** variable to be yourself.

weefig actually sets the author through weechat.register. Having two different authors set two different ways may be confusing to future users. Also, because weefig is not a module, the **author** variable is not needed at all.

Thank you, 

Emmett Underhill

**Comment by Ian-Stewart-Binks** [comment]
Ah, now I see.

**Pull request merged**
